version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./sbom-output:/app/sbom-output
      - ./vulnerability-reports:/app/vulnerability-reports
    command: node index.js
  
  sbom-generator:
    build: .
    volumes:
      - ./sbom-output:/app/sbom-output
    command: ./generate-sbom.sh
  
  vulnerability-checker:
    build: .
    volumes:
      - ./sbom-output:/app/sbom-output
      - ./vulnerability-reports:/app/vulnerability-reports
    command: ./vulnerability-check.sh
